# Generated by Django 3.0.8 on 2020-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255, unique=True)),
                ('element_tag', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=255)),
                ('element_img', models.ImageField(upload_to='elements/')),
                ('creator_tag', models.CharField(max_length=255)),
                ('creator_link', models.CharField(max_length=255)),
            ],
        ),
    ]
